package com;

/**
 * Created by WIZE02 on 31/07/2018.
 */

public class Constants {
    public String retMgnetCallsBuilder(){
        String CREATE_mgnet_calls=
                "CREATE TABLE " + " mgnet_calls " + "("
                        + "CallID" +  " INTEGER, "
                        + "AID"+  " INTEGER, "
                        + "CID"+  " INTEGER, "
                        + "CreateDate"+ " TEXT, "
                        + "EndDate"+ " TEXT, "
                        + "CallEmail"+ " TEXT, "
                        + "statusID"+  " INTEGER, "
                        + "CallPriority"+ " TEXT, "
                        + "subject"+ " TEXT, "
                        + "comments"+ " TEXT, "
                        + "IsClose"+  " INTEGER, "
                        + "IsRead"+  " INTEGER, "
                        + "CallType"+ " TEXT, "
                        + "CallReminderDate"+ " TEXT, "
                        + "CallUpdate"+ " TEXT, "
                        + "resolution"+ " TEXT, "
                        + "cntrctDate"+ " TEXT, "
                        + "TechnicianID"+  " INTEGER, "
                        + "statusName"+ " TEXT, "
                        + "PcatID"+  " INTEGER, "
                        + "internalSN"+ " TEXT, "
                        + "Pmakat"+ " TEXT, "
                        + "Pname"+ " TEXT, "
                        + "contractID"+ " TEXT, "
                        + "Cphone"+ " TEXT, "
                        + "OriginID"+  " INTEGER, "
                        + "ProblemTypeID"+  " INTEGER, "
                        + "CallTypeID"+  " INTEGER, "
                        + "priorityID"+  " TEXT, "
                        + "OriginName"+ " TEXT, "
                        + "problemTypeName"+ " TEXT, "
                        + "CallTypeName"+ " TEXT, "
                        + "Cname"+ " TEXT, "
                        + "Cemail"+ " TEXT, "
                        + "contctCode"+  " INTEGER, "
                        + "callStartTime"+ " TEXT, "
                        + "callEndTime"+ " TEXT, "
                        + "Ccompany"+ " TEXT, "
                        + "Clocation"+ " TEXT, "
                        + "callOrder"+  " INTEGER, "
                        + "Caddress"+ " TEXT, "
                        + "Ccity"+ " TEXT, "
                        + "Ccomments"+ " TEXT, "
                        + "Cfname"+ " TEXT, "
                        + "Clname"+ " TEXT, "
                        + "techName"+ " TEXT, "
                        + "Aname"+ " TEXT, "
                        + "ContctName"+ " TEXT, "
                        + "ContctAddress"+ " TEXT, "
                        + "ContctCity"+ " TEXT, "
                        + "ContctCell"+ " TEXT, "
                        + "ContctPhone"+ " TEXT, "
                        + "Ccell"+ " TEXT, "
                        + "techColor"+ " TEXT, "
                        + "ContctCemail"+ " TEXT, "
                        + "CallParentID"+ " TEXT, "
                        + "state"+ " TEXT, "
                        + "sla"+ " TEXT "
                        + ")";
        return CREATE_mgnet_calls;
    }
    public String retLeadsBuilder(){
        String CREATE_Leads = "CREATE TABLE " + "Leads" + "("
                +"OID" +  " TEXT, "
                +"CID" +  " TEXT, "
                +"Odate" +  " TEXT, "
                +"ccName" +  " TEXT, "
                +"ccID" +  " TEXT, "
                +"ccType" +  " TEXT, "
                +"ccNum" +  " TEXT, "
                +"ccExp" +  " TEXT, "
                +"CCpayment" +  " TEXT, "
                +"Oshipping" +  " TEXT, "
                +"Osum" +  " TEXT, "
                +"Sfname" +  " TEXT, "
                +"Slname" +  " TEXT, "
                +"Saddress" +  " TEXT, "
                +"Scity" +  " TEXT, "
                +"Scountry" +  " TEXT, "
                +"Sstate" +  " TEXT, "
                +"Szip" +  " TEXT, "
                +"Sphone" +  " TEXT, "
                +"Scell" +  " TEXT, "
                +"Semail" +  " TEXT, "
                +"Scomment" +  " TEXT, "
                +"Oprint" +  " TEXT, "
                +"Ofile" +  " TEXT, "
                +"PStypeID" +  " TEXT, "
                +"PSaleID" +  " TEXT, "
                +"Ostatus" +  " TEXT, "
                +"OBstatus" +  " TEXT, "
                +"OpaymentType" +  " TEXT, "
                +"LNG" +  " TEXT, "
                +"PsupplierID" +  " TEXT, "
                +"Ocard" +  " TEXT, "
                +"Oinvoice" +  " TEXT, "
                +"OnotHome" +  " TEXT, "
                +"OtimeShipping" +  " TEXT, "
                +"OdateShipping" +  " TEXT, "
                +"Orate" +  " TEXT, "
                +"Ocoin" +  " TEXT, "
                +"Expr1" +  " TEXT, "
                +"OstatusName" +  " TEXT, "
                +"CparentName" +  " TEXT, "
                +"CParentID" +  " TEXT, "
                +"CparentUsername" +  " TEXT, "
                +"Ocomment" +  " TEXT, "
                +"Otax" +  " TEXT, "
                +"Sfax" +  " TEXT, "
                +"Omakats" +  " TEXT, "
                +"Cfax" +  " TEXT, "
                +"OwnerID" +  " TEXT, "
                +"Ofname" +  " TEXT, "
                +"Olname" +  " TEXT, "
                +"Ccompany" +  " TEXT, "
                +"ProdSum" +  " TEXT, "
                +"CJoinerID" +  " TEXT, "
                +"PsupplierNAME" +  " TEXT, "
                +"SUsername" +  " TEXT, "
                +"PsupplierLOGO" +  " TEXT, "
                +"SPassword" +  " TEXT, "
                +"Cusername" +  " TEXT, "
                +"Oemail" +  " TEXT, "
                +"OUdate" +  " TEXT, "
                +"OTdate" +  " TEXT, "
                +"CTypeID" +  " TEXT, "
                +"CTypeName" +  " TEXT, "
                +"OcommentID" +  " TEXT, "
                +"SID" +  " TEXT, "
                +"Oref" +  " TEXT, "
                +"Cusername2" +  " TEXT "
                + ")";
        return CREATE_Leads;
    }
    public String retISActionsBuilder(){
        String CREATE_IS_Actions = "CREATE TABLE " + "IS_Actions" + "("
                + "actionID" + " INTEGER,"
                +"taskID"+ " INTEGER,"
                +"actionDate" + " TEXT,"
                +"actionStartDate" + " TEXT,"
                +"actionDue" + " TEXT,"
                +"actionDesc" + " TEXT,"
                +"comments" + " TEXT,"
                +"priorityID"+ " INTEGER,"
                +"statusID"+ " INTEGER,"
                +"reminderID" + " TEXT,"
                +"ownerID"+ " INTEGER,"
                +"userID"+ " INTEGER,"
                +"WorkHours"+ " TEXT,"
                +"WorkEstHours"+ " TEXT,"
                +"[Create]"+ " TEXT,"
                +"LastUpdate"+ " TEXT,"
                +"actionLink"+ " TEXT,"
                +"depID"+ " INTEGER,"
                +"actionRef"+ " TEXT,"
                +"userCfname"+ " TEXT,"
                +"userClname"+ " TEXT,"
                +"userCemail"+ " TEXT,"
                +"userCtypeID"+ " INTEGER,"
                +"ownerCfname"+ " TEXT,"
                +"ownerClname"+ " TEXT,"
                +"ownerCemail"+ " TEXT,"
                +"ownerCtypeID"+ " INTEGER,"
                +"projectID"+ " INTEGER,"
                +"statusName"+ " TEXT,"
                +"PriorityName"+ " TEXT,"
                +"actionType"+ " TEXT,"
                +"actionSdate"+ " TEXT,"
                +"actionEdate"+ " TEXT,"
                +"WorkHoursM"+ " TEXT,"
                +"WorkEstHoursM"+ " TEXT,"
                +"actionPrice"+ " TEXT,"
                +"statusColor"+ " TEXT,"
                +"taskSummery"+ " TEXT,"
                +"projectSummery"+ " TEXT,"
                +"projectType"+ " TEXT,"
                +"actionNum"+ " TEXT,"
                +"actionFrom"+ " TEXT,"
                +"actionDays"+ " TEXT,"
                +"ParentActionID"+ " INTEGER,"
                +"remindertime"+ " TEXT,"
                +"Expr1"+ " TEXT,"
                +"projectDesc" + " TEXT"
                + ")";
        return CREATE_IS_Actions;
    }
    public String retCcustomersBuilder(){
        String CREATE_Ccustomers = "CREATE TABLE " + "Ccustomers" + "("

                +"CID" + " TEXT,"
                +"CParentID" + " TEXT,"
                +"TargetWeight" + " TEXT,"
                +"Cusername" + " TEXT,"
                +"Cpassword" + " TEXT,"
                +"Cfname" + " TEXT,"
                +"Clname" + " TEXT,"
                +"Cemail" + " TEXT,"
                +"Caddress" + " TEXT,"
                +"Ccity" + " TEXT,"
                +"CArea" + " TEXT,"
                +"Ccountry" + " TEXT,"
                +"Cstate" + " TEXT,"
                +"Czip" + " TEXT,"
                +"Cphone" + " TEXT,"
                +"Ccell" + " TEXT,"
                +"Cfax" + " TEXT,"
                +"Cdate" + " TEXT,"
                +"CBirthDate" + " TEXT,"
                +"CStartDate" + " TEXT,"
                +"CEndDate" + " TEXT,"
                +"CFemilyStatus" + " TEXT,"
                +"CBuySum" + " TEXT,"
                +"Ccompany" + " TEXT,"
                +"Cprofession" + " TEXT,"
                +"LNG" + " TEXT,"
                +"CTypeID" + " TEXT,"
                +"CCodeID" + " TEXT,"
                +"CConfirm" + " TEXT,"
                +"CInterest" + " TEXT,"
                +"Cduty" + " TEXT,"
                +"CPoints" + " TEXT,"
                +"SendEmail" + " TEXT,"
                +"ccName" + " TEXT,"
                +"ccID" + " TEXT,"
                +"ccType" + " TEXT,"
                +"ccNo" + " TEXT,"
                +"ccExp" + " TEXT,"
                +"ccpayment" + " TEXT,"
                +"CStatus" + " TEXT,"
                +"CstatusName" + " TEXT,"
                +"Cage" + " TEXT,"
                +"CIMG" + " TEXT,"
                +"CSex" + " TEXT,"
                +"Ccomments" + " TEXT,"
                +"CJoinerID" + " TEXT,"
                +"Cweb" + " TEXT,"
                +"CstatusID" + " TEXT,"
                +"CstatusDate" + " TEXT,"
                +"CstatusID2" + " TEXT,"
                +"CstatusDate2" + " TEXT,"
                +"IsActive" + " TEXT,"
                +"Herb_ID" + " TEXT,"
                +"Age" + " TEXT,"
                +"Weight" + " TEXT,"
                +"LooseWeight" + " TEXT,"
                +"Height" + " TEXT,"
                +"AgentID" + " TEXT,"
                +"LastLogin" + " TEXT,"
                +"SlpCode" + " TEXT,"
                +"LastPassword" + " TEXT,"
                +"CTypeName" + " TEXT,"
                +"Longtitude" + " TEXT,"
                +"Latitude" + " TEXT,"
                +"Link" + " TEXT,"
                +"Distance" + " TEXT"
                + ")";






        return CREATE_Ccustomers;
    }
    public String retCPBuilder(){
        String cp ="CREATE TABLE " + " ControlPanel " + "("
                + " _key " +  " TEXT PRIMARY KEY,"
                + " _value " + " TEXT, "
                + " _description " + " TEXT "
                + ")";
        return cp;
    }
    public String retCall_OfflineBuilder(){
        String CREATE_call_offline=
                "CREATE TABLE " + "call_offline" + "("
                        + "CallID" +  " INTEGER, "
                        + "statusID"+  " INTEGER, "
                        + "internalSN"+ " TEXT, "
                        + "techAnswer"+ " TEXT "
                        + ")";
        return CREATE_call_offline;
    }
    public String retCallTimeBuilder(){
        String CREATE_call_time =
                "CREATE TABLE " + "Calltime" + "("
                        + "CTID" + " INTEGER PRIMARY KEY AUTOINCREMENT, "
                        + "CallID" +  " INTEGER, "
                        + "CallStartTime" +  " TEXT, "
                        + "Minute" + " TEXT, "
                        + "CTcomment" + " TEXT, "
                        + "ctq" + " TEXT "
                        + ")";
        return CREATE_call_time;
    }
    public String retISActionsTimeBuilder(){
        String CREATE_IS_ActionsTime=
                "CREATE TABLE " + "IS_ActionsTime" + "("
                        + "ID" +  " INTEGER PRIMARY KEY AUTOINCREMENT, "
                        + "CID"+  " TEXT, "
                        + "ActionID"+ " TEXT, "
                        + "ActionStart"+ " TEXT, "
                        + "ActionEnd"+ " TEXT "
                        + ")";
        return CREATE_IS_ActionsTime;
    }
}
